import xmltodict
from datetime import datetime
import textwrap
import time #timestamp
from functools import wraps
import shutil #used to confirm Nmap is installed in system
import json #used in xml_to_json function and for future parsing
import re #regex used for input validation
import os #used to set API key and check existence of file for deletion
#Used to run Nmap with validated input and shell=False
import subprocess # nosec B404
import argparse #used to parse arguments passed to program
import ipaddress #used for ipv6 implementation
#following functions used for logging and spinner function
#spinner function should be replaced with estimated/elapsed time for running function
import sys
import itertools
import threading
import functools
import logging
# XML comes from Nmap output generated by the tool
import xmltodict
from google import genai #LLM
# Rich library components used to create styled progress bars
# and live terminal output
from rich.progress import (
    Progress,
    BarColumn,
    TextColumn,
    TimeRemainingColumn,
    SpinnerColumn
)
from rich.console import Console
from functools import wraps

BANNER = r"""
  ____                       ____                     _
 |  _ \ ___  ___ ___  _ _   / ___|_   _  __ _ _ __ __| |
 | |_) / _ \/ __/ _ \| '_ \| |  _| | | |/ _` | '__/ _` |
 |  _ <  __/ (_| (_) | | | | |_| | |_| | (_| | | | (_| |
 |_| \_\___|\___\___/|_| |_|\____|\__,_|\__,_|_|  \__,_|
"""

MODEL_NAME = "gemini-3-flash-preview"
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "").strip()
logging.basicConfig(
    filename="app.log",
    level=logging.INFO,
    format='%(asctime)s - %(message)s'
)

# Creates a Rich console object for styled CLI output
console = Console()

# LOGGING AND PROGRESS DISPLAY
def progress_output(message):
    def decorator(func):
        @wraps(func)
        def wrapper(*args, **kwargs):
            logging.info(f"TASK START: {message}")

            result_container = {}

            def run_function():
                try:
                    result_container["result"] = func(*args, **kwargs)
                except Exception as e:
                    result_container["error"] = e

            try:
                thread = threading.Thread(target=run_function)
                start_time = time.perf_counter()
                thread.start()

                with Progress(
                    SpinnerColumn(),
                    TextColumn("[cyan]{task.description:<25}"),
                    BarColumn(bar_width=40),
                    TextColumn("[magenta]{task.percentage:>3.0f}%"),
                    console=console,
                ) as progress:
                    task = progress.add_task(message, total=100)
                    current = 0

                    while thread.is_alive():
                        if current < 95:
                            current += 1
                        progress.update(task, completed=current)
                        time.sleep(0.08)

                    thread.join()

                    if "error" in result_container:
                        progress.update(task, completed=current)
                    else:
                        progress.update(task, completed=100)

                duration = time.perf_counter() - start_time

                if "error" in result_container:
                    error = result_container["error"]
                    logging.error(f"FAILED: {message} | Error: {error}")
                    console.print(f"[red]✗[/red] {message} failed after {duration:.2f}s")
                    raise error

                logging.info(f"COMPLETED: {message} (Duration: {duration:.2f}s)")
                console.print(f"[green]✓[/green] {message} completed in {duration:.2f}s")

                return result_container["result"]

            except KeyboardInterrupt:
                logging.info(f"CANCELLED: {message}")
                raise

        return wrapper
    return decorator

#GET TARGET IP
def get_target():

    print(BANNER)
    print("ReconGuard v1.0 | Defensive Recon Tool\n")
    print("Press Ctrl+C at any time to exit.\n")
    
    parser = argparse.ArgumentParser(
        description="",
        formatter_class=argparse.RawTextHelpFormatter
    )

    parser.add_argument(
        "-t",
        "--target",
        required=True,
        help="Target private IPv4/IPv6 address or loopback address (example: 192.168.1.10, 127.0.0.1, ::1)"
    )
    
    args = parser.parse_args()
    return validate_input(args.target)

#VALIDATE INPUT
def validate_input(targetIP):
    """
    Validate the user-provided target IP.

    Allows:
    - Private or loopback IPv4 addresses
    - Private or loopback IPv6 addresses

    Rejects:
    - Public IP addresses
    - Invalid IP formats
    - Command-injection characters such as ;, &, |, `, $, <, >, and \
    """

    dangerous_chars = r"[;&|`$<>\\]"

    # Make sure input exists
    if targetIP is None:
        raise ValueError("Invalid target. Target cannot be empty.")

    # Remove extra spaces before/after the target
    targetIP = targetIP.strip()

    if not targetIP:
        raise ValueError("Invalid target. Target cannot be empty.")

    # Reject command injection characters
    if re.search(dangerous_chars, targetIP):
        raise ValueError("Invalid target. Command characters are not allowed.")

    try:
        ip = ipaddress.ip_address(targetIP)

        # Allow safe IPv4 targets: private ranges and loopback
        if isinstance(ip, ipaddress.IPv4Address):
            if ip.is_private or ip.is_loopback:
                return str(ip)

            raise ValueError("Invalid target. Only private or loopback IPv4 addresses are allowed.")

        # Allow safe IPv6 targets: private ranges and loopback
        if isinstance(ip, ipaddress.IPv6Address):
            if ip.is_private or ip.is_loopback:
                return str(ip).split("%")[0]

            raise ValueError("Invalid target. Only private or loopback IPv6 addresses are allowed.")

    except ValueError as error:
        if "Invalid target" in str(error):
            raise

        raise ValueError("Invalid format. Please enter a valid IPv4 or IPv6 address.")
                    
#CONSTRUCT COMMAND
def nmap_command(validatedIP):
    #build nmap command to run with target IP
    #nmap -sV <targetIP> -oX scan.xml
    #XML IS READABLE MID-SCAN. SEARCH FOR MITIGATIONS
    ip = ipaddress.ip_address(validatedIP)

    if isinstance(ip, ipaddress.IPv6Address):
        return ["nmap", "-6", "-sV", "-oX", "scan.xml", validatedIP]

    return ["nmap", "-sV", "-oX", "scan.xml", validatedIP]

#RUN COMMAND
@progress_output("Scanning with Nmap")
def run_command(command):
    # Command is constructed as a list from validated input
    subprocess.run(command, capture_output=True, text=True) # nosec B603


#XML TO JSON
@progress_output("Converting to JSON    ")
def xml_json(path: str, isFile: bool = False) -> dict:
    # Scan.xml is generated by local Nmap execution and deleted after parsing
    parsedXml = None
    try:
        if isFile:
            with open(path, "r", encoding="utf-8") as f:
                parsedXml = xmltodict.parse(f.read())
        else:
            parsedXml = xmltodict.parse(path)
    except FileNotFoundError:
        print(f"Error: The file '{path}' was not found.")
        return {"hosts": []}
    except Exception as e:
        print(f"Error parsing XML data: {e}")
        return {"hosts": []}

    # Extract the root Nmap execution element
    nmapRun = parsedXml.get("nmaprun", {})
    rawHosts = nmapRun.get("host", [])

    if isinstance(rawHosts, dict):
        rawHosts = [rawHosts]

    result = {"hosts": []}

    for host in rawHosts:
        ipAddress = None
        addresses = host.get("address", [])
        if isinstance(addresses, dict):
            addresses = [addresses]
        
        for addr in addresses:
            if addr.get("@addrtype") == "ipv4":
                ipAddress = addr.get("@addr")
                break

        hostnamesBlock = host.get("hostnames", {})
        hostnameEntry = hostnamesBlock.get("hostname", {}) if hostnamesBlock else {}
        
        if isinstance(hostnameEntry, list) and len(hostnameEntry) > 0:
            hostName = hostnameEntry[0].get("@name")
        else:
            hostName = hostnameEntry.get("@name", "Unknown")

        hostStatus = host.get("status", {}).get("@state", "unknown")

        cleanPorts = []
        portsContainer = host.get("ports", {})
        
        if portsContainer:
            portList = portsContainer.get("port", [])
            
            if isinstance(portList, dict):
                portList = [portList]

            for port in portList:
                serviceBlock = port.get("service", {}) if port.get("service") else {}
                
                portData = {
                    "port": port.get("@portid"),
                    "protocol": port.get("@protocol"),
                    "state": port.get("state", {}).get("@state"),
                    "service": serviceBlock.get("@name", "unknown"),
                    "product": serviceBlock.get("@product", ""),
                    "version": serviceBlock.get("@version", "")
                }
                cleanPorts.append(portData)

        result["hosts"].append({
            "name": hostName,
            "ip": ipAddress,
            "status": hostStatus,
            "ports": cleanPorts
        })

    return result
    
#RULE BASED DETECTION
#FILTERS OUT NOISE
def rules(data: dict) -> dict:
    hostsList = data.get("hosts", [])
    if isinstance(hostsList, dict):
        hostsList = [hostsList]
        
    filteredData = {"hosts": []}
    
    for host in hostsList:
        if host.get("status") != "up":
            continue
            
        cleanPorts = []
        rawPorts = host.get("ports", [])
        if isinstance(rawPorts, dict):
            rawPorts = [rawPorts]
            
        for p in rawPorts:
            if p.get("state") == "open":
                
                rawData = {
                    "port": p.get("port"),
                    "protocol": p.get("protocol"),
                    "service": p.get("service"),
                    "product": p.get("product"),
                    "version": p.get("version")
                }
                
                sanitizedPort = {k: v for k, v in rawData.items() if v}
                
                cleanPorts.append(sanitizedPort)
                
        if cleanPorts:
            filteredData["hosts"].append({
                "ip": host.get("ip"),
                "hostname": host.get("name", "Unknown"),
                "open_ports": cleanPorts
            })
            
    return filteredData


#PROMPT GENERATION
def generate_prompt(report):
    return f"""
View this from the perspective of a cybersecurity network analyst.

JSON:
{json.dumps(report, indent=2)}

Based on the provided JSON extracted from an Nmap report, do the following:

- Create a list of devices connected to the network
- Explain the Nmap reports findings in plain language
- List any recommendations to improve security
- Present recommendations as a numbered list, each number on a new line
- Sort recommendations based on severity
- Respond ONLY in valid JSON format:
- Create a list of devices connected to the network.
- Identify each meaningful open service as a separate security finding.
- Assign a severity level to each finding: Critical, High, Medium, Low, or Informational.
- Explain the risk in plain language.
- List potential risks.
- Categorize recommended actions by priority: high, medium, and low.
- Respond ONLY in valid JSON format.

Use this exact JSON structure:


{{
    "devices": [
        {{
            "device_name": "...",
            "ip_address": "...",
            "description": "..."
        }}
    ],
    "findings": [
        {{
            "title": "...",
            "severity": "Critical/High/Medium/Low/Informational",
            "host": "...",
            "ip_address": "...",
            "port": "...",
            "service": "...",
            "version": "...",
            "status": "...",
            "risk_summary": "...",
            "potential_risks": [
                "...",
                "..."
            ],
            "recommended_actions": {{
                "high": [
                    "..."
                ],
                "medium": [
                    "..."
                ],
                "low": [
                    "..."
                ]
            }}
        }}
    ]
}}
"""

#LLM CALL
@progress_output("Sending prompt to Gemini  ")
def call_LLM(prompt):
    
    client = genai.Client(api_key=GEMINI_API_KEY)
    response = client.models.generate_content(
        model = MODEL_NAME,
        contents=prompt
    )
    responseText = response.text.strip() if response.text else ""
    if responseText.startswith("```"):
        responseText = responseText.strip("`")
        responseText = responseText.replace("json", "", 1).strip()
    return json.loads(responseText)

#REPORT GENERATION
@progress_output("Printing report")
def print_report(report, filename="report.txt"):
    devices = report.get("devices", [])
    findings = report.get("findings", [])

    def wrap_text(text, width=75, indent=""):
        return textwrap.fill(
            str(text),
            width=width,
            initial_indent=indent,
            subsequent_indent=indent
        )

    def wrap_bullet(text, width=75):
        return textwrap.fill(
            f"• {text}",
            width=width,
            subsequent_indent="  "
        )

    with open(filename, "w", encoding="utf-8") as file:

        print("=" * 60, file=file)
        print("RECONGUARD SECURITY REPORT", file=file)
        print("=" * 60, file=file)

        scan_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        print(f"\nScan Time     : {scan_time}", file=file)
        print(f"Generated By  : ReconGuard v1.0", file=file)

        

        print("\nCONNECTED DEVICES", file=file)
        print("-" * 60, file=file)

        for i, device in enumerate(devices, 1):
            print(
                f"{i}. {device.get('device_name', 'Unknown')} "
                f"({device.get('ip_address', 'N/A')})",
                file=file
            )

            description = device.get("description", "No description available.")
            print(wrap_text(description, indent="   Description: "), file=file)

        print("\n" + "=" * 60, file=file)
        print("ANALYSIS AND RECOMMENDATIONS", file=file)
        print("=" * 60, file=file)

        for i, finding in enumerate(findings, 1):
            title = finding.get("title", "Security Finding")
            severity = finding.get("severity", "Informational")

            print(f"\nFINDING #{i} — {title}", file=file)
            print("=" * 60, file=file)

            print(f"Severity      : {severity}", file=file)
            print(
                f"Host          : {finding.get('host', 'N/A')} "
                f"({finding.get('ip_address', 'N/A')})",
                file=file
            )
            print(f"Port          : {finding.get('port', 'N/A')}", file=file)
            print(f"Service       : {finding.get('service', 'N/A')}", file=file)
            print(f"Version       : {finding.get('version', 'N/A')}", file=file)
            print(f"Status        : {finding.get('status', 'N/A')}", file=file)

            print("\n" + "-" * 60, file=file)
            print("RISK SUMMARY", file=file)
            print("-" * 60, file=file)
            print(wrap_text(finding.get("risk_summary", "No risk summary provided.")), file=file)

            print("\n" + "-" * 60, file=file)
            print("POTENTIAL RISKS", file=file)
            print("-" * 60, file=file)

            risks = finding.get("potential_risks", [])
            if risks:
                for risk in risks:
                    print(wrap_bullet(risk), file=file)
            else:
                print("• No specific risks listed.", file=file)

            print("\n" + "-" * 60, file=file)
            print("RECOMMENDED ACTIONS", file=file)
            print("-" * 60, file=file)

            actions = finding.get("recommended_actions", {})

            for level in ["high", "medium", "low"]:
                items = actions.get(level, [])
                if items:
                    print(f"\n[{level.upper()}]", file=file)
                    for item in items:
                        print(wrap_bullet(item), file=file)

    print("Report complete.")

#FILE DELETION
def remove_file(filename):
    if os.path.exists(filename):
        os.remove(filename)
# main
def main():
    try:
        if not shutil.which("nmap"):
            print("Error: Nmap is not installed. Please install Nmap first.")
            return

        if not GEMINI_API_KEY:
            raise ValueError("Set GEMINI_API_KEY environment variable first.")

        validIP = get_target()

        command = nmap_command(validIP)
        run_command(command)

        unfilteredData = xml_json("scan.xml", isFile=True)
        filteredData = rules(unfilteredData)
        remove_file("scan.xml")

        if not filteredData.get("hosts"):
            print("Scan completed successfully, but no open ports or active services were detected.")
            return

        prompt = generate_prompt(filteredData)
        report = call_LLM(prompt)

        print_report(report)

    except KeyboardInterrupt:
        console.print("\n[yellow]Scan cancelled by user.[/yellow]")

    except ValueError as error:
        print(f"Error: {error}")
        sys.exit(1)

    except FileNotFoundError:
        print("Error: Required file was not found. Please try running the scan again.")

    except Exception as error:
        error_text = str(error)

        if "503" in error_text or "UNAVAILABLE" in error_text:
            print("Error: Gemini is temporarily unavailable or under high demand. Please try again later.")

        elif "GEMINI_API_KEY" in error_text:
            print("Error: Gemini API key is missing. Please set the GEMINI_API_KEY environment variable.")

        else:
            print(f"Error details: {error}")


if __name__ == "__main__":
    main()
