import ipaddress #used for ipv6 implementation
import xmltodict
from src.reporter import progress_output

#VALIDATE INPUT
def validate_input(targetIP):
    try:
        ip = ipaddress.ip_address(targetIP)

        # Allow safe IPv4 targets: private ranges and loopback
        if isinstance(ip, ipaddress.IPv4Address):
            if ip.is_private or ip.is_loopback:
                return str(ip)
            raise ValueError("Invalid target. Only private or loopback IPv4 addresses are allowed.")

        # Allow safe IPv6 targets: private ranges and loopback
        if isinstance(ip, ipaddress.IPv6Address):
            if ip.is_private or ip.is_loopback:
                return str(ip).split("%")[0]
            raise ValueError("Invalid target. Only private or loopback IPv6 addresses are allowed.")

    except ValueError as error:
        if "Invalid target" in str(error):
            raise

        raise ValueError("Invalid format. Please enter a valid IPv4 or IPv6 address.")

#XML TO JSON
@progress_output("Converting to JSON    ")
def xml_json(path: str, isFile: bool = False) -> dict:
    # Scan.xml is generated by local Nmap execution and deleted after parsing
    parsedXml = None
    try:
        if isFile:
            with open(path, "r", encoding="utf-8") as f:
                parsedXml = xmltodict.parse(f.read())
        else:
            parsedXml = xmltodict.parse(path)
    except FileNotFoundError:
        print(f"Error: The file '{path}' was not found.")
        return {"hosts": []}
    except Exception as e:
        print(f"Error parsing XML data: {e}")
        return {"hosts": []}

    # Extract the root Nmap execution element
    nmapRun = parsedXml.get("nmaprun", {})
    rawHosts = nmapRun.get("host", [])

    if isinstance(rawHosts, dict):
        rawHosts = [rawHosts]

    result = {"hosts": []}

    for host in rawHosts:
        ipAddress = None
        addresses = host.get("address", [])
        if isinstance(addresses, dict):
            addresses = [addresses]
        
        for addr in addresses:
            if addr.get("@addrtype") == "ipv4":
                ipAddress = addr.get("@addr")
                break

        hostnamesBlock = host.get("hostnames", {})
        hostnameEntry = hostnamesBlock.get("hostname", {}) if hostnamesBlock else {}
        
        if isinstance(hostnameEntry, list) and len(hostnameEntry) > 0:
            first_entry = hostnameEntry[0]
            hostName = first_entry.get("@name", "Unknown") if isinstance(first_entry, dict) else "Unknown"
        elif isinstance(hostnameEntry, dict):
            hostName = hostnameEntry.get("@name", "Unknown")
        else:
            hostName = "Unknown"

        hostStatus = host.get("status", {}).get("@state", "unknown")

        cleanPorts = []
        portsContainer = host.get("ports", {})
        
        if portsContainer:
            portList = portsContainer.get("port", [])
            
            if isinstance(portList, dict):
                portList = [portList]

            for port in portList:
                serviceBlock = port.get("service", {}) if port.get("service") else {}
                
                portData = {
                    "port": port.get("@portid"),
                    "protocol": port.get("@protocol"),
                    "state": port.get("state", {}).get("@state"),
                    "service": serviceBlock.get("@name", "unknown"),
                    "product": serviceBlock.get("@product", ""),
                    "version": serviceBlock.get("@version", "")
                }
                cleanPorts.append(portData)

        result["hosts"].append({
            "name": hostName,
            "ip": ipAddress,
            "status": hostStatus,
            "ports": cleanPorts
        })

    return result

#RULE BASED DETECTION
#FILTERS OUT NOISE
def rules(data: dict) -> dict:
    hostsList = data.get("hosts", [])
    if isinstance(hostsList, dict):
        hostsList = [hostsList]
        
    filteredData = {"hosts": []}
    
    for host in hostsList:
        if host.get("status") != "up":
            continue
            
        cleanPorts = []
        rawPorts = host.get("ports", [])
        if isinstance(rawPorts, dict):
            rawPorts = [rawPorts]
            
        for p in rawPorts:
            if p.get("state") == "open":
                
                rawData = {
                    "port": p.get("port"),
                    "protocol": p.get("protocol"),
                    "service": p.get("service"),
                    "product": p.get("product"),
                    "version": p.get("version")
                }
                
                sanitizedPort = {k: v for k, v in rawData.items() if v}
                
                cleanPorts.append(sanitizedPort)
                
        if cleanPorts:
            filteredData["hosts"].append({
                "ip": host.get("ip"),
                "hostname": host.get("name", "Unknown"),
                "open_ports": cleanPorts
            })
            
    return filteredData