import io
import json
import os
import time #timestamp
import threading
import logging
from functools import wraps
from src.config import DEFAULT_REPORT_FILE
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from pypdf import PdfReader, PdfWriter
from rich.progress import (
    Progress,
    BarColumn,
    TextColumn,
    SpinnerColumn
)
from rich.console import Console

console = Console()

# LOGGING AND PROGRESS DISPLAY
def progress_output(message):
    def decorator(func):
        @wraps(func)
        def wrapper(*args, **kwargs):
            logging.info(f"TASK START: {message}")

            result_container = {}

            def run_function():
                try:
                    result_container["result"] = func(*args, **kwargs)
                except Exception as e:
                    result_container["error"] = e

            try:
                thread = threading.Thread(target=run_function)
                start_time = time.perf_counter()
                thread.start()

                with Progress(
                    SpinnerColumn(),
                    TextColumn("[cyan]{task.description:<25}"),
                    BarColumn(bar_width=40),
                    TextColumn("[magenta]{task.percentage:>3.0f}%"),
                    console=console,
                ) as progress:
                    task = progress.add_task(message, total=100)
                    current = 0

                    while thread.is_alive():
                        if current < 95:
                            current += 1
                        progress.update(task, completed=current)
                        time.sleep(0.08)

                    thread.join()

                    if "error" in result_container:
                        progress.update(task, completed=current)
                    else:
                        progress.update(task, completed=100)

                duration = time.perf_counter() - start_time

                if "error" in result_container:
                    error = result_container["error"]
                    logging.error(f"FAILED: {message} | Error: {error}")
                    console.print(f"[red]✗[/red] {message} failed after {duration:.2f}s")
                    raise error

                logging.info(f"COMPLETED: {message} (Duration: {duration:.2f}s)")
                console.print(f"[green]✓[/green] {message} completed in {duration:.2f}s")

                return result_container["result"]

            except KeyboardInterrupt:
                logging.info(f"CANCELLED: {message}")
                raise

        return wrapper
    return decorator

def build_from_json(json_data):
    if isinstance(json_data, str):
        data = json.loads(json_data)
    elif isinstance(json_data, dict):
        data = json_data
    else:
        raise TypeError("Expected json_data to be string or dictionary container.")

    pdf_buffer = io.BytesIO()

    doc = SimpleDocTemplate(pdf_buffer, pagesize=letter, leftMargin=54, rightMargin = 54, topMargin=54, bottomMargin=54)

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle('DocTitle', parent=styles['Heading1'], fontSize=24, textColor=colors.HexColor("#1A365D"), spaceAfter=15)
    subtitle_style = ParagraphStyle('DocSubtitle', parent=styles['Normal'], fontName='Helvetica-Oblique', fontSize=10, textColor=colors.HexColor('#718096'), spaceAfter=15)
    section_style = ParagraphStyle('SectionHeader', parent=styles['Heading2'], fontSize=16, textColor=colors.HexColor("#2C5282"), spaceBefore=18, spaceAfter=8)
    finding_title = ParagraphStyle('FindingTitle', parent=styles['Heading3'], fontSize=12, fontName='Helvetica-Bold', spaceBefore=14, spaceAfter=4)
    body_style = ParagraphStyle('BodyText', parent=styles['Normal'], fontSize=10, leading=14, textColor=colors.HexColor("#2D3748"))
    bullet_style = ParagraphStyle('BulletText', parent=body_style, leftIndent=15, firstLineIndent=-10, spaceAfter=2)

    story = []

    story.append(Paragraph("RECONGUARD SECURITY REPORT", title_style))
    scan_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    subtitle_text = (f"\nScan Time     : {scan_time}\nGenerated By  : ReconGuard v1.0")
    story.append(Paragraph(subtitle_text, subtitle_style))

    if "devices" in data and data["devices"]:
        story.append(Paragraph("CONNECTED DEVICES", section_style))
        table_data = [[Paragraph("<b>Device Name</b>", body_style),
                       Paragraph("<b>IP Address</b>", body_style),
                       Paragraph("<b>Description</b>", body_style)
                       ]]
        for dev in data["devices"]:
            table_data.append([
                Paragraph(dev.get("device_name", "N/A"), body_style),
                Paragraph(dev.get("ip_address", "N/A"), body_style),
                Paragraph(dev.get("description", "No description provided."), body_style)
            ])
        
        device_table = Table(table_data, colWidths=[130, 114, 260])
        device_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#F1F5F9")),
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
            ('TOPPADDING', (0,0), (-1,-1), 6),
            ('BOTTOMPADDING', (0,0), (-1,-1), 6),
            ('LINEBELOW', (0,0), (-1,-1), 0.5, colors.HexColor("#E2E8F0")),
        ]))
        story.append(device_table)
        story.append(Spacer(1, 15))

    if "findings" in data and data["findings"]:
        story.append(Paragraph("Security Assessment Findings", section_style))
        
        for finding in data["findings"]:
            # Severity Color-Coding Dict
            severity = finding.get("severity", "Informational")
            sev_colors = {
                "critical": "#742A2A", # Deep Maroon
                "high": "#C53030",     # Alert Red
                "medium": "#DD6B20",   # Warning Orange
                "low": "#3182CE",      # Soft Blue
                "informational": "#4A5568" # Slate Grey
            }
            assigned_color = sev_colors.get(severity.lower(), "#4A5568")
            
            # Formatted Title Banner
            title_text = f"{finding.get('title', 'Vulnerability Flag')} — <font color='{assigned_color}'><b>[{severity.upper()}]</b></font>"
            story.append(Paragraph(title_text, finding_title))
            
            # Target Context Table (A mini-grid containing Host/Port/Service environment variables)
            context_data = [
                [Paragraph(f"<b>Host Target:</b> {finding.get('host', 'N/A')} ({finding.get('ip_address', 'N/A')})", body_style),
                 Paragraph(f"<b>Service:</b> {finding.get('service', 'N/A')} (v{finding.get('version', 'Unknown')})", body_style)],
                [Paragraph(f"<b>Target Port:</b> {finding.get('port', 'N/A')}", body_style),
                 Paragraph(f"<b>Status:</b> {finding.get('status', 'N/A')}", body_style)]
            ]
            context_table = Table(context_data, colWidths=[252, 252])
            context_table.setStyle(TableStyle([
                ('VALIGN', (0,0), (-1,-1), 'TOP'),
                ('BOTTOMPADDING', (0,0), (-1,-1), 2),
                ('TOPPADDING', (0,0), (-1,-1), 2),
            ]))
            story.append(context_table)
            story.append(Spacer(1, 6))
            
            # Risk Summary Paragraph
            story.append(Paragraph(f"<b>Risk Summary:</b> {finding.get('risk_summary', 'No summary available.')}", body_style))
            story.append(Spacer(1, 4))
            
            # Unpacking Potential Risks List Block
            risks = finding.get("potential_risks", [])
            if risks:
                story.append(Paragraph("<b>Potential Exploitation Risks:</b>", body_style))
                for r in risks:
                    story.append(Paragraph(f"• {r}", bullet_style))
                story.append(Spacer(1, 4))
                
            # Unpacking Recommended Actions Dictionary Matrix
            rec_actions = finding.get("recommended_actions", {})
            if rec_actions:
                story.append(Paragraph("<b>Recommended Actions Roadmap:</b>", body_style))
                
                # Check priority columns inside the recommendations map
                for priority in ["high", "medium", "low"]:
                    actions_list = rec_actions.get(priority, [])
                    for act in actions_list:
                        action_text = f"<b>[{priority.upper()}]</b> {act}"
                        story.append(Paragraph(f"• {action_text}", bullet_style))
            
            # Structural divider line tracking between distinct vulnerabilities
            story.append(Spacer(1, 10))
            
    doc.build(story)
    pdf_buffer.seek(0)
    return pdf_buffer

@progress_output("Encrypting report")
def print_report(report, password):
    raw_buffer = build_from_json(report)
    reader = PdfReader(raw_buffer)
    writer = PdfWriter()

    for page in reader.pages:
        writer.add_page(page)

    writer.encrypt(user_password=password, algorithm="AES-256")
    with open(DEFAULT_REPORT_FILE, "wb") as secure_file:
        writer.write(secure_file)

#FILE DELETION
def remove_file(filename):
    if os.path.exists(filename):
        os.remove(filename)