# src/io_handler.py
from src.io_handler import progress_output
import subprocess # nosec B404
import ipaddress
import xmltodict

#CONSTRUCT COMMAND
def nmap_command(validatedIP):
    ip = ipaddress.ip_address(validatedIP)

    command = ["nmap", "-sV"]

    # Add IPv6 mode if needed
    if isinstance(ip, ipaddress.IPv6Address):
        command.append("-6")

    command.extend([validatedIP, "-oX", "scan.xml"])

    return command

#RUN COMMAND
@progress_output("Scanning with Nmap    ")
def run_command(command):
    # Command is constructed as a list from validated input
    subprocess.run(command, capture_output=True, text=True) # nosec B603

#XML TO JSON
@progress_output("Converting to JSON    ")
def xml_json(path: str, isFile: bool = False) -> dict:
    # Scan.xml is generated by local Nmap execution and deleted after parsing
    try:
        if isFile:
            with open(path, "r", encoding="utf-8") as f:
                parsedXml = xmltodict.parse(f.read())
        else:
            parsedXml = xmltodict.parse(path)
    except FileNotFoundError:
        print(f"Error: The file '{path}' was not found.")
        return {"hosts": []}
    except Exception as e:
        print(f"Error parsing XML data: {e}")
        return {"hosts": []}

    # Extract the root Nmap execution element
    nmapRun = parsedXml.get("nmaprun", {})
    rawHosts = nmapRun.get("host", [])

    if isinstance(rawHosts, dict):
        rawHosts = [rawHosts]

    result = {"hosts": []}

    for host in rawHosts:
        ipAddress = None
        addresses = host.get("address", [])
        if isinstance(addresses, dict):
            addresses = [addresses]
        
        for addr in addresses:
            if addr.get("@addrtype") == "ipv4":
                ipAddress = addr.get("@addr")
                break

        hostnamesBlock = host.get("hostnames", {})
        hostnameEntry = hostnamesBlock.get("hostname", {}) if hostnamesBlock else {}
        
        if isinstance(hostnameEntry, list) and len(hostnameEntry) > 0:
            hostName = hostnameEntry[0].get("@name")
        else:
            hostName = hostnameEntry.get("@name", "Unknown")

        hostStatus = host.get("status", {}).get("@state", "unknown")

        cleanPorts = []
        portsContainer = host.get("ports", {})
        
        if portsContainer:
            portList = portsContainer.get("port", [])
            
            if isinstance(portList, dict):
                portList = [portList]

            for port in portList:
                serviceBlock = port.get("service", {}) if port.get("service") else {}
                
                portData = {
                    "port": port.get("@portid"),
                    "protocol": port.get("@protocol"),
                    "state": port.get("state", {}).get("@state"),
                    "service": serviceBlock.get("@name", "unknown"),
                    "product": serviceBlock.get("@product", ""),
                    "version": serviceBlock.get("@version", "")
                }
                cleanPorts.append(portData)

        result["hosts"].append({
            "name": hostName,
            "ip": ipAddress,
            "status": hostStatus,
            "ports": cleanPorts
        })

    return result

#RULE BASED DETECTION
#FILTERS OUT NOISE
def rules(data: dict) -> dict:
    hostsList = data.get("hosts", [])
    if isinstance(hostsList, dict):
        hostsList = [hostsList]
        
    filteredData = {"targets": []}
    
    for host in hostsList:
        if host.get("status") != "up":
            continue
            
        cleanPorts = []
        rawPorts = host.get("ports", [])
        if isinstance(rawPorts, dict):
            rawPorts = [rawPorts]
            
        for p in rawPorts:
            if p.get("state") == "open":
                
                rawData = {
                    "port": p.get("port"),
                    "protocol": p.get("protocol"),
                    "service": p.get("service"),
                    "product": p.get("product"),
                    "version": p.get("version")
                }
                
                sanitizedPort = {k: v for k, v in rawData.items() if v}
                
                cleanPorts.append(sanitizedPort)
                
        if cleanPorts:
            filteredData["targets"].append({
                "ip": host.get("ip"),
                "hostname": host.get("name", "Unknown"),
                "open_ports": cleanPorts
            })
            
    return filteredData